In [171]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random as rd

In [172]:
optdigits_df=pd.read_csv('optdigits_csv.csv')
optdigits_df.head()

input1  input2  input3  input4  input5  input6  input7  input8  input9  \
0       0       1       6      15      12       1       0       0       0   
1       0       0      10      16       6       0       0       0       0   
2       0       0       8      15      16      13       0       0       0   
3       0       0       0       3      11      16       0       0       0   
4       0       0       5      14       4       0       0       0       0   

   input10  ...  input56  input57  input58  input59  input60  input61  \
0        7  ...        0        0        0        6       14        7   
1        7  ...        0        0        0       10       16       15   
2        1  ...        0        0        0        9       14        0   
3        0  ...        0        0        0        0        1       15   
4        0  ...        0        0        0        4       12       14   

   input62  input63  input64  class  
0        1        0        0      0  
1        3        0        0      0  
2        0        0        0      7  
3        2        0        0      4  
4        7        0        0      6  

[5 rows x 65 columns]

In [173]:
optdigits_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5620 entries, 0 to 5619
Data columns (total 65 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   input1   5620 non-null   int64
 1   input2   5620 non-null   int64
 2   input3   5620 non-null   int64
 3   input4   5620 non-null   int64
 4   input5   5620 non-null   int64
 5   input6   5620 non-null   int64
 6   input7   5620 non-null   int64
 7   input8   5620 non-null   int64
 8   input9   5620 non-null   int64
 9   input10  5620 non-null   int64
 10  input11  5620 non-null   int64
 11  input12  5620 non-null   int64
 12  input13  5620 non-null   int64
 13  input14  5620 non-null   int64
 14  input15  5620 non-null   int64
 15  input16  5620 non-null   int64
 16  input17  5620 non-null   int64
 17  input18  5620 non-null   int64
 18  input19  5620 non-null   int64
 19  input20  5620 non-null   int64
 20  input21  5620 non-null   int64
 21  input22  5620 non-null   int64
 22  input23  5620 non-null  

In [174]:
optdigits_df.describe()

input1       input2       input3       input4       input5  \
count  5620.0  5620.000000  5620.000000  5620.000000  5620.000000   
mean      0.0     0.302135     5.393238    11.815480    11.578292   
std       0.0     0.879962     4.672719     4.255952     4.462546   
min       0.0     0.000000     0.000000     0.000000     0.000000   
25%       0.0     0.000000     1.000000    10.000000     9.000000   
50%       0.0     0.000000     5.000000    13.000000    13.000000   
75%       0.0     0.000000     9.000000    15.000000    15.000000   
max       0.0     8.000000    16.000000    16.000000    16.000000   

            input6       input7       input8       input9      input10  ...  \
count  5620.000000  5620.000000  5620.000000  5620.000000  5620.000000  ...   
mean      5.593772     1.379359     0.138256     0.003203     1.971174  ...   
std       5.631149     3.356633     1.046998     0.090423     3.098815  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      10.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    16.000000     5.000000    16.000000  ...   

           input56      input57      input58      input59      input60  \
count  5620.000000  5620.000000  5620.000000  5620.000000  5620.000000   
mean      0.166904     0.000356     0.281851     5.760498    11.989680   
std       0.843455     0.018863     0.929969     5.021145     4.347542   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     1.000000    10.000000   
50%       0.000000     0.000000     0.000000     5.000000    13.000000   
75%       0.000000     0.000000     0.000000    10.000000    15.000000   
max      13.000000     1.000000    10.000000    16.000000    16.000000   

           input61      input62      input63      input64        class  
count  5620.000000  5620.000000  5620.000000  5620.000000  5620.000000  
mean     11.572420     6.720819     2.093594     0.254093     4.495196  
std       4.975675     5.815564     4.047959     1.418558     2.868131  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       9.000000     0.000000     0.000000     0.000000     2.000000  
50%      13.000000     6.000000     0.000000     0.000000     4.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 65 columns]

In [175]:
X_test = optdigits_df.iloc[:,:].values
print(X_test.shape)

(5620, 65)


In [176]:
X = optdigits_df.iloc[:,0:64].values
print(X)

[[ 0  1  6 ...  1  0  0]
 [ 0  0 10 ...  3  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0  1 ...  6  0  0]
 [ 0  0  2 ... 12  0  0]
 [ 0  0 10 ... 12  1  0]]


In [177]:
X_result = optdigits_df.iloc[:,64].values

In [178]:
K=10
m=5620
Centroids=np.array([]).reshape(64,0)
# for i in range(K):
#     rand=rd.randint(0,m-1)
#     Centroids=np.c_[Centroids,X[rand]]
i = 0
while(i<10):
    rand=rd.randint(0,m-1)
    if(X_test[rand,64] == i):
        Centroids=np.c_[Centroids,X[rand]]
        i = i + 1
    
print(Centroids)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  3.  0.  7.  0. 12.  8.  9.  0.  1.]
 [12. 13. 12. 16.  5.  8. 16. 16.  8. 12.]
 [12. 10. 16. 15. 15.  8.  5. 16. 14. 12.]
 [ 3.  1. 10.  2.  0.  7.  0. 13.  9. 13.]
 [ 0.  0.  0.  0.  0.  0.  0. 12.  0.  8.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  7.  0.  3.  0.  0.  0.  0.]
 [ 9.  3. 10. 15.  0. 16. 16.  6.  9. 12.]
 [13. 16. 15.  7. 12. 16.  9.  6. 15. 10.]
 [ 5. 16. 15. 12. 12. 11.  0.  8. 16.  4.]
 [14.  4. 13. 10.  0.  7.  0. 14. 15.  7.]
 [ 0.  0.  0.  0.  0.  0.  0. 15.  0. 13.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  8.  0.  2.  6.  0.  4.  0.]
 [15.  1.  9.  6.  0. 14. 16.  0. 15. 15.]
 [ 3. 16.  6.  0. 16.  1.  2.  0.  5. 10.]
 [ 0. 16. 16. 10.  8.  0.  0.  5.  8.  4.]
 [10.  2.  7. 12.  0.  0.  0. 16. 14.  9.]
 [ 2.  0.  0.  0.  0.  0.  0.  4.  0. 14.]
 [ 0.  0.  

In [179]:
num_iter=100
Output={}
for n in range(100):
    #step 2.a
    EuclidianDistance=np.array([]).reshape(m,0)
    for k in range(K):
        tempDist=np.sum((X-Centroids[:,k])**2,axis=1)
#         print('tempDist' , k)
#         print(tempDist)
#         print('\n')
        EuclidianDistance=np.c_[EuclidianDistance,tempDist]
#         print('EuclidianDistance' , k)
#         print(EuclidianDistance)
#         print('\n')
#     print("Euclidian")
#     print(EuclidianDistance)
#     print(EuclidianDistance.shape)
    C=np.argmin(EuclidianDistance,axis=1)+1
#     print(C.shape)
#     print(np.argmin(EuclidianDistance,axis=1)+1)
    
    #step 2.b
    Y={}
    Z={}
    for k in range(K):
        Y[k+1]=np.array([]).reshape(64,0)
        Z[k+1]=np.array([]).reshape(65,0)
    for i in range(m):
        Y[C[i]]=np.c_[Y[C[i]],X[i]]
        Z[C[i]]=np.c_[Z[C[i]],X_test[i]]
     
    for k in range(K):
        Y[k+1]=Y[k+1].T
        
        
    for k in range(K):
        Centroids[:,k]=np.mean(Y[k+1],axis=0)
        
    Output=Z


In [180]:
Centroids

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [2.72232305e-02, 4.24528302e-02, 9.75332068e-01, 4.52708907e-01,
        2.06611570e-03, 7.13024283e-01, 1.41093474e-02, 2.92259084e-01,
        2.54174397e-01, 1.13314448e-02],
       [4.47549909e+00, 2.95047170e+00, 1.05996205e+01, 7.74104683e+00,
        2.41735537e-01, 8.69315673e+00, 1.92768959e+00, 6.32069510e+00,
        6.11688312e+00, 3.71104816e-01],
       [1.32050817e+01, 1.19646226e+01, 1.40891841e+01, 1.37649219e+01,
        6.13636364e+00, 1.30883002e+01, 1.10264550e+01, 1.33886256e+01,
        1.24526902e+01, 3.68555241e+00],
       [1.10490018e+01, 1.19363208e+01, 6.86907021e+00, 1.25876951e+01,
        1.19917355e+01, 1.39757174e+01, 8.40740741e+00, 1.39652449e+01,
        1.24916512e+01, 1.16657224e+01],
       [2.70961887e+00, 3.79009434e+00, 7.30550285e-01, 5.17814509e+00,
   

In [181]:
for i  in range(0,10):
    print("cluster "+str(i))
    print(Output[i+1][64])
    


cluster 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0